name: Android e2e
on: workflow_dispatch

defaults:
  run:
    shell: 'bash'

jobs:
  e2e-tests-android:
    name: '[Placeholder] Running e2e android tests'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependency
        run: sudo apt-get update && sudo apt-get install -y libpulse0

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version-file: .java-version
          cache: gradle

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Restore node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('yarn.lock') }}

      - name: Install packages if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Install detox-cli globally
        run: |
          npm install detox-cli --global

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          MY_APP_MODE: mocked
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          avd-name: RN_APP
          script: |
            chmod +x ./android/gradlew
            # npx react-native build-android --mode=release
            detox build --configuration android.emu.release
            detox test --configuration android.emu.release

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts
          path: artifacts

      # - name: Build Detox for Android Emulator
      #   run: detox build --configuration android.emu.release

      # - name: Run Detox tests for Android Emulator
      #   run: detox test --configuration android.emu.release --cleanup
