name: Android e2e
on: workflow_dispatch

defaults:
  run:
    shell: 'bash'

jobs:
  e2e-tests-android:
    name: '[Placeholder] Running e2e android tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version-file: .java-version
          cache: gradle

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Restore node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('yarn.lock') }}

      - name: Install packages if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install react-native-cli globally
        run: npm install -g react-native-cli

      - name: Install detox-cli globally
        run: npm install -g detox-cli

      - name: Create Android Emulator
        run: |
          echo "y" | sdkmanager "system-images;android-29;default;x86_64"
          echo "no" | avdmanager create avd --force --name RN_APP --device "pixel" --package "system-images;android-29;default;x86_64" --tag "default" --abi "x86_64"

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./android/gradlew

      - name: Build Detox for Android Emulator
        run: detox build --configuration android.emu.release

      - name: Run Detox tests for Android Emulator
        run: detox test --configuration android.emu.release --cleanup
