name: Android e2e
on: workflow_dispatch

defaults:
  run:
    shell: 'bash'

jobs:
  e2e-tests-android:
    name: '[Placeholder] Running e2e android tests'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependency
        run: sudo apt-get update && sudo apt-get install -y libpulse0

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version-file: .java-version
          cache: gradle

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Restore node_modules
        id: cache
        uses: actions/cache@v4
        with:
          path: 'node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('yarn.lock') }}

      - name: Install packages if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install react-native-cli globally
        run: npm install -g react-native-cli

      - name: Install detox-cli globally
        run: npm install -g detox-cli

      - name: Install emulator
        run: |
          sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "emulator"

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          avd-name: RN_APP
          script: ./gradlew connectedCheck

      # - name: Make Gradle Wrapper Executable
      #   run: chmod +x ./android/gradlew

      # - name: Build Detox for Android Emulator
      #   run: detox build --configuration android.emu.release

      # - name: Run Detox tests for Android Emulator
      #   run: detox test --configuration android.emu.release --cleanup
